#! /bin/bash
WLANNM=$(cat /root/brscript/wlanmon.txt)
export WLANNM
printf '\033]2;CAPTURING IVs\a'
echo -e "Deixe-me aberto"
sleep 1
airodump-ng --bssid $WEPB -c $WEPC -w /root/handshakes/WEP/$WEPF $WLANNM
